version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/a"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/b"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/c"
    schedule:
      interval: "weekly"
